require("Resources/Script/ActorStates_Constants.lua")
function EsperSkill_EsperBeam(Power)
  STATE:SetMoveBoxMultiplier(1)
  STATE:EnableCameraShake(true, false, 200)
  STATE:SetCameraShakeFactor1(200, 50, 30)
  STATE:SetCameraShakeFactor2(10, 60, 1000, 1500)
  STATE:SetUseAttack(true)
  STATE:SetStateMinSp(0)
  STATE:SetCoolTime(120000)
  STATE:InitLua(700, 300, true)
  STATE:SetEtcSkillStateEnter(true)
  STATE:SetFlyAnchoringStateEnter(false)
  local range = ACTION:GetRange()
  Attack1 = CreateCAttack()
  Attack1:InitAttack1(WEAPONTYPE_UNUSED, ATTACKATTRIB_ESPERSKILL_ESPERBEAM, 300, Power * 25, 0)
  Attack1:InitAttack2(MAKEBOX(MAKEVECTOR3(0, 250, -60), MAKEVECTOR3(0, 0, -1), range * 0.6, range * 0.8, range * 4), 1, 1, false)
  AddAttack(ATTACKS, Attack1)
end
function EsperSkill_EsperCoat(Power)
  STATE:SetStateMinSp(10)
  STATE:InitLua(500, 0, true)
  STATE:SetCoolTime(30000)
  STATE:SetEtcSkillStateEnter(true)
  STATE:SetFlyAnchoringStateEnter(false)
  STATE:SetConditionTime(5000)
end
function EsperSkill_EsperBomb(Power)
  STATE:SetMoveBoxMultiplier(0.5)
  STATE:EnableCameraShake(true, false, 600)
  STATE:SetCameraShakeFactor1(200, 50, 30)
  STATE:SetCameraShakeFactor2(10, 60, 2000, 3000)
  STATE:SetUseAttack(true)
  STATE:SetStateMinSp(0)
  STATE:SetEtcSkillStateEnter(true)
  STATE:SetFlyAnchoringStateEnter(true)
  STATE:SetMidAirAttackState(false)
  STATE:SetIgnoreActorCollision(true)
  STATE:InitLua(1000, 0, 1000, false)
  STATE:SetCoolTime(60000)
  local range = ACTION:GetRange()
  Attack1 = CreateCAttack()
  Attack1:InitAttack1(WEAPONTYPE_UNUSED, ATTACKATTRIB_ESPERSKILL_ESPER_BOMB, 550, Power, 0)
  Attack1:InitAttack2(MAKECYLINDER(MAKEVECTOR3(0, 200, 0), 800, range * 1), 1, 1, false)
  Attack1:AddLightningBombMK2Condition(5000, 0.5)
  Attack1:AddBlowCondition(1000, 4000)
  AddAttack(ATTACKS, Attack1)
end
function EsperSkill_EsperKneeSlide(Power)
  STATE:SetMoveBoxMultiplier(0.65)
  STATE:SetStateMinSp(25)
  STATE:SetCoolTime(0)
  STATE:SetEtcSkillStateEnter(true)
  STATE:SetFlyAnchoringStateEnter(false)
  STATE:SetLotateLimit(false, 0, 0)
  STATE:SetDirectionLimit(false)
  STATE:InitLua(600, 0, false)
end
function AttackAttribute_EsperSetSkill()
  local currAttackAttrib
  currAttackAttrib = AttackAttribIndexer:GetAttackAttrib(ATTACKATTRIB_ESPERSKILL_ESPERBEAM)
  currAttackAttrib:SetDir(DIR_FRONT, PART_MIDDLE)
  currAttackAttrib:SetPower(POWER_STRONG, DESTROY_BLASTOBJECT_DAMAGE_10)
  currAttackAttrib:SetWeaponType(WEAPONTYPE_UNUSED)
  currAttackAttrib:SetCounterAttack(COUNTERATTACK_DISABLE)
  currAttackAttrib:SetGuardData(0, GUARDCRUSH_ENABLE)
  currAttackAttrib:SetDamageData(1, DAMAGEMOVING_DISABLE, DAMAGEBYPART_DISABLE)
  currAttackAttrib:SetDamageSequence("Resources/Effects/weapon_mindshock_body.seq", "Resources/Effects/weapon_mindshock_body.seq", "Resources/Sound/rail_blast.ogg", "Resources/Sound/rail_blast.ogg")
  currAttackAttrib:SetAttackSequence("Resources/Effects/blank_1sec.seq", "Resources/Sound/bsword_s.ogg")
  currAttackAttrib:SetKillMessageImage("Resources/Image/EsperAction/Esperaction.png", 32, 32)
  currAttackAttrib = AttackAttribIndexer:GetAttackAttrib(ATTACKATTRIB_ESPERSKILL_ESPER_BOMB)
  currAttackAttrib:SetDir(DIR_FRONT, PART_MIDDLE)
  currAttackAttrib:SetPower(POWER_STRONG, DESTROY_BLASTOBJECT_DAMAGE_50)
  currAttackAttrib:SetWeaponType(WEAPONTYPE_UNUSED)
  currAttackAttrib:SetCounterAttack(COUNTERATTACK_DISABLE)
  currAttackAttrib:SetGuardData(0, GUARDCRUSH_ENABLE)
  currAttackAttrib:SetDamageData(1000, DAMAGEMOVING_DISABLE, DAMAGEBYPART_DISABLE)
  currAttackAttrib:SetDamageSequence("Resources/Effects/backattack_sword_s.seq", "Resources/Effects/backattack_sword_s.seq", "Resources/Sound/airgun_blast.ogg", "Resources/Sound/airgun_blast.ogg")
  currAttackAttrib:SetAttackSequence("Resources/Effects/blank_1sec.seq", "")
  currAttackAttrib:SetKillMessageImage("Resources/Image/EsperAction/Esperaction.png", 32, 32)
end
