LoadStringTable("Language/Script/Arcade_char_string_table.x7")
KICHI = GetString("KICHI")
MOTHER_VIRUS = GetString("MOTHER_VIRUS")
BROKEN_FAM107 = GetString("BROKEN_FAM107")
INFECTED_TEAJO = GetString("INFECTED_TEAJO")
INJURYED_TEAJO = GetString("INJURYED_TEAJO")
