require("Resources/Script/ActorStates_Constants.lua")
local index = 0
MONINPUT_NORMAL = index
index = index + 1
MONINPUT_RUN = index
index = index + 1
MONINPUT_DAMAGE = index
index = index + 1
MONINPUT_BLOW = index
index = index + 1
MONINPUT_DEATH = index
index = index + 1
MONINPUT_ATTACK_0 = index
index = index + 1
MONINPUT_ATTACK_1 = index
index = index + 1
MONINPUT_ATTACK_2 = index
index = index + 1
MONINPUT_PRE_FASTRUN = index
index = index + 1
MONINPUT_FASTRUN = index
index = index + 1
MONINPUT_MOVE_ATTACK = index
index = index + 1
MONINPUT_TOTAL = index
index = index + 1
index = 0
MONSTATE_NORMAL = index
index = index + 1
MONSTATE_RUN = index
index = index + 1
MONSTATE_DAMAGE = index
index = index + 1
MONSTATE_BLOW = index
index = index + 1
MONSTATE_DEATH = index
index = index + 1
MONSTATE_ATTACK_0 = index
index = index + 1
MONSTATE_ATTACK_1 = index
index = index + 1
MONSTATE_ATTACK_2 = index
index = index + 1
MONSTATE_PRE_FASTRUN = index
index = index + 1
MONSTATE_FASTRUN = index
index = index + 1
MONSTATE_MOVE_ATTACK = index
index = index + 1
MONSTATE_TOTAL = index
index = index + 1
index = 0
MONMOVE_WAYPOINT = index
index = index + 1
MONMOVE_ACTOR = index
index = index + 1
MONMOVE_TOTAL = index
index = index + 1
index = 0
MONPATTERN_MISSION_PUPPET = index
index = index + 1
MONPATTERN_MISSION_RETURN = index
index = index + 1
MONPATTERN_MISSION_ATTACK = index
index = index + 1
MONPATTERN_DEFFNCE_ATTACK = index
index = index + 1
MONPATTERN_TOTAL = index
index = index + 1
