require("Resources/Script/ActorStates_Constants.lua")
function StandardRevolver(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetFrontOffset(275)
  STATE:InitLua(260, 40, -40, 250, 800, 650)
  Attack1 = CreateCAttack()
  Attack1:InitAttack1(WEAPONTYPE_REVOLVER, ATTACKATTRIB_REVOLVER, 150, Power * 0.25 + AdditionalPower, AddtionalPower)
  Attack1:InitAttack2(MAKERAY(MAKEVECTOR3(0, 0, 0), MAKEVECTOR3(0, 0.02, -1), RayDistanceLimit), 1, 1, false)
  Attack1:SetDamageApplyType(3)
  Attack1:SetDistanceDamageLength(3000)
  Attack1:SetCollisionRangeAdjust(false, false)
  Attack1:SetConsumeAmmo(1)
  Attack1:SetCameraShakeEnable(true, true, 0)
  Attack1:AddPushCondition(100, 1700, -5000)
  Attack1:SetCameraShakeSetFactor1(50, 25, 20)
  Attack1:SetCameraShakeSetFactor2(1, 1, 1000, 1500)
  Attack1:SetCameraShakeRandomDir(true)
  AddAttack(ATTACKS, Attack1)
  Attack2 = CreateCAttack()
  Attack2:InitAttack1(WEAPONTYPE_REVOLVER, ATTACKATTRIB_REVOLVER, 150, Power * 0.25 + AdditionalPower, AddtionalPower)
  Attack2:InitAttack2(MAKERAY(MAKEVECTOR3(0, 0, 0), MAKEVECTOR3(0, -0.5 * Accuracy, -1), RayDistanceLimit), 1, 1, false)
  Attack2:SetDamageApplyType(3)
  Attack2:SetDistanceDamageLength(3000)
  Attack2:SetCollisionRangeAdjust(false, false)
  Attack2:AddPushCondition(100, 1700, -5000)
  AddAttack(ATTACKS, Attack2)
  Attack3 = CreateCAttack()
  Attack3:InitAttack1(WEAPONTYPE_REVOLVER, ATTACKATTRIB_REVOLVER, 150, Power * 0.25 + AdditionalPower, AddtionalPower)
  Attack3:InitAttack2(MAKERAY(MAKEVECTOR3(0, 0, 0), MAKEVECTOR3(0.5 * Accuracy, 0.5 * Accuracy, -1), RayDistanceLimit), 1, 1, false)
  Attack3:SetDamageApplyType(3)
  Attack3:SetDistanceDamageLength(3000)
  Attack3:SetCollisionRangeAdjust(false, false)
  Attack3:AddPushCondition(100, 1700, -5000)
  AddAttack(ATTACKS, Attack3)
  Attack4 = CreateCAttack()
  Attack4:InitAttack1(WEAPONTYPE_REVOLVER, ATTACKATTRIB_REVOLVER, 150, Power * 0.25 + AdditionalPower, AddtionalPower)
  Attack4:InitAttack2(MAKERAY(MAKEVECTOR3(0, 0, 0), MAKEVECTOR3(-0.5 * Accuracy, 0.5 * Accuracy, -1), RayDistanceLimit), 1, 1, false)
  Attack4:SetCollisionRangeAdjust(false, false)
  Attack4:AddPushCondition(100, 1700, -5000)
  AddAttack(ATTACKS, Attack4)
end
