function LightningBomberMk2_Explosion(damage, range)
  EXPLOSIONATTACK:InitAttack1(WEAPONTYPE_LIGHT_BOMB, ATTACKATTRIB_LIGHT_BOMBER_MK2, 0, damage, 0)
  EXPLOSIONATTACK:InitAttack2(MAKECYLINDER(MAKEVECTOR3(POSITION:GetX(), POSITION:GetY() + 250, POSITION:GetZ()), 600, 600), 1, 1)
  EXPLOSIONATTACK:SetFriendlyDamage(0.5, 0.2)
  EXPLOSIONATTACK:SetGaussRandomDamage(10, 30, 100, 1)
  EXPLOSIONATTACK:SetGaussRandomCritical(50)
  EXPLOSIONATTACK:AddLightningBombMK2Condition(2500, 0.5)
end
function StandardLightningMK2Init()
  GRENADE:InitLua(-4000, 16, 300, 100, 1)
  GRENADE:SetDamping(0.5, 6, 0.9)
  GRENADE:SetDamageType(2)
  GRENADE:SetCollisionChar(0, true)
  GRENADE:SetSpeedCheck(true, 200)
  GRENADE:SetSequence("Resources/Effects/weapon_Lightning_bomber_ex.seq", "Resources/Effects/weapon_lbomber_mk2_throw.seq", "Resources/Effects/weapon_lbomber_mk2_throw.seq", "Resources/Effects/weapon_lbomber_mk2_fire.seq", "Resources/Effects/weapon_lbomber_mk2_fire.seq")
  GRENADE:SetExplosionSound("Resources/Sound/lightningbomber_bomb.ogg")
  GRENADE:SetExplosionReadySound("Resources/Sound/Earthbomber_limit.ogg")
  GRENADE:SetExplosionLuaName("LightningBomberMk2_Explosion")
  GRENADE:SetCollisionRange(MAKECYLINDER(MAKEVECTOR3(0, 200, 0), 600, 600))
end
function StandardLightningBomberMK2(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:InitLua(100, "Resources/Effects/skill_gunner_electronic_bomb_1.seq", "Resources/Sound/earthbomber_shot.ogg", 500, 4750)
  STATE:SetWeaponInitLuaFuncName("StandardLightningMK2Init")
end
