require("Resources/Script/ActorStates_Constants.lua")
function StandardRescueGunMK2Launch(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:InitLua(100, "Resources/Effects/skill_gunner_electronic_bomb_1.seq", "Resources/Sound/rescuegun_shot.ogg", 500, 5000)
  STATE:SetWeaponInitLuaFuncName("StandardRescueGunMK2Init")
end
function StandardRescueGunMK2Init()
  GRENADE:InitLua(-4500, 16, 2600, 100, 1)
  GRENADE:SetDamping(0.5, 16, 0.9)
  GRENADE:SetDamageType(3)
  GRENADE:SetCollisionChar(3, false)
  GRENADE:SetSpeedCheck(true, 200)
  GRENADE:SetSequence("Resources/Effects/weapon_resque_fire02.seq", "Resources/Effects/weapon_rescuemk2_hp_ball01.seq", "Resources/Effects/weapon_rescuemk2_hp_ball01_enemy.seq", "Resources/Effects/weapon_rescuemk2_hp_ball02.seq", "Resources/Effects/weapon_rescuemk2_hp_ball02_enemy.seq")
  GRENADE:SetExplosionSound("Resources/Sound/rescuegun_bomb.ogg")
  GRENADE:SetExplosionLuaName("StandardRescueGunMK2Explosion")
  GRENADE:SetAfterActiveCheckChar(true)
end
function StandardRescueGunMK2Explosion(damage, range)
  EXPLOSIONATTACK:InitAttack1(WEAPONTYPE_RESCUEGUN, ATTACKATTRIB_RESCUEGUN, 0, damage, 0)
  EXPLOSIONATTACK:InitAttack2(MAKESPHERE(MAKEVECTOR3(POSITION:GetX(), POSITION:GetY(), POSITION:GetZ()), range), 1, 1)
  EXPLOSIONATTACK:InitAttack3(true, false)
  EXPLOSIONATTACK:SetDamageApplyType(0)
  EXPLOSIONATTACK:SetFriendlyDamage(0, 1)
  EXPLOSIONATTACK:SetUiCriticalExplosionAttack(false)
  EXPLOSIONATTACK:SetExceptSentry(true)
  EXPLOSIONATTACK:SetCritical(1, 0)
end
function StandardRescueGunMK2Launch_Ammo(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:InitLua(100, "Resources/Effects/skill_gunner_electronic_bomb_1.seq", "Resources/Sound/rescuegun_shot.ogg", 500, 4000)
  STATE:SetWeaponInitLuaFuncName("StandardRescueGunMK2Init_Ammo")
end
function StandardRescueGunMK2Init_Ammo()
  GRENADE:InitLua(-4500, 16, 3200, 100, 1)
  GRENADE:SetDamping(0.5, 16, 0.9)
  GRENADE:SetDamageType(3)
  GRENADE:SetCollisionChar(3, false)
  GRENADE:SetSpeedCheck(true, 200)
  GRENADE:SetSequence("Resources/Effects/weapon_resque_fire03.seq", "Resources/Effects/weapon_rescuemk2_ammo_ball01.seq", "Resources/Effects/weapon_rescuemk2_ammo_ball01_enemy.seq", "Resources/Effects/weapon_rescuemk2_ammo_ball02.seq", "Resources/Effects/weapon_rescuemk2_ammo_ball02_enemy.seq")
  GRENADE:SetExplosionSound("Resources/Sound/rescuegun_bomb.ogg")
  GRENADE:SetExplosionLuaName("StandardRescueGunMK2Explosion_Ammo")
  GRENADE:SetAfterActiveCheckChar(true)
end
function StandardRescueGunMK2Explosion_Ammo(damage, range)
  EXPLOSIONATTACK:InitAttack1(WEAPONTYPE_RESCUEGUN, ATTACKATTRIB_RESCUEGUN, 0, damage, 0)
  EXPLOSIONATTACK:InitAttack2(MAKESPHERE(MAKEVECTOR3(POSITION:GetX(), POSITION:GetY(), POSITION:GetZ()), range), 1, 1)
  EXPLOSIONATTACK:InitAttack3(false, true)
  EXPLOSIONATTACK:SetDamageApplyType(0)
  EXPLOSIONATTACK:SetFriendlyDamage(0, 0)
  EXPLOSIONATTACK:SetUiCriticalExplosionAttack(false)
  EXPLOSIONATTACK:SetExceptSentry(true)
  EXPLOSIONATTACK:SetCritical(1, 0)
end
