require("Resources/Script/ActorStates_Constants.lua")
function StandardBreakerJumpDash(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetDrop(200, MAKEVECTOR3(0, -20000, 0))
  STATE:SetStealthCancel(true)
  STATE:EnableCameraShake(true, false, 500)
  STATE:SetCameraShakeFactor1(200, 30, 20)
  STATE:SetCameraShakeFactor2(60, 0, 2000, 3000)
  STATE:InitLua(300, 550, 40, false)
  local range = WEAPON:GetRange()
  Attack = CreateCAttack()
  Attack:InitAttack1(WEAPONTYPE_BREAKER, ATTACKATTRIB_BREAKER_SWORD_JUMPDASH, 250, Power * 1 + AdditionalPower, AdditionalPower)
  Attack:InitAttack2(MAKEBOX(MAKEVECTOR3(0, 0, -100), MAKEVECTOR3(0, 0, -1), range * 1, range * 1.2, range * 1.2), 1, 1, false)
  Attack:AddPushCondition(100, 5000, -2000)
  AddAttack(ATTACKS, Attack)
end
function StandardBreakerAfterDash1(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetMoveBoxMultiplier(1)
  STATE:SetStealthCancel(true)
  STATE:SetHitStop(220, 320)
  STATE:EnableCameraShake(true, false, 220)
  STATE:SetCameraShakeFactor1(200, 30, 20)
  STATE:SetCameraShakeFactor2(60, 0, 2000, 3000)
  STATE:InitLua(600, 500, 40, true)
  local range = WEAPON:GetRange()
  Attack1 = CreateCAttack()
  Attack1:InitAttack1(WEAPONTYPE_BREAKER, ATTACKATTRIB_BREAKER_SWORD_ATTACK1, 200, Power + AdditionalPower, AdditionalPower)
  Attack1:InitAttack2(MAKEBOX(MAKEVECTOR3(0, 200, 0), MAKEVECTOR3(0, 0, -1), range * 1.5, range * 0.7, range * 1), 1, 1, false)
  Attack1:AddBlowCondition(2000, 3000)
  AddAttack(ATTACKS, Attack1)
end
function StandardBreakerStandAttack_Strong(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetMoveBoxMultiplier(1)
  STATE:SetStealthCancel(true)
  STATE:SetHitStop(220, 320)
  STATE:EnableCameraShake(true, false, 220)
  STATE:SetCameraShakeFactor1(200, 30, 20)
  STATE:SetCameraShakeFactor2(60, 0, 2000, 3000)
  STATE:InitLua(600, 500, 40, true)
  local range = WEAPON:GetRange()
  Attack1 = CreateCAttack()
  Attack1:InitAttack1(WEAPONTYPE_BREAKER, ATTACKATTRIB_BREAKER_SWORD_ATTACK1, 200, Power + AdditionalPower, AdditionalPower)
  Attack1:InitAttack2(MAKEBOX(MAKEVECTOR3(0, 200, 0), MAKEVECTOR3(0, 0, -1), range * 1.5, range * 0.7, range * 1), 1, 1, false)
  Attack1:AddBlowCondition(2000, 3000)
  AddAttack(ATTACKS, Attack1)
end
function StandardBreakerGatherGuage(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetMoveSpeedRate(0.7)
  STATE:SetStealthCancel(true)
  STATE:SetHitStop(150, 300)
  STATE:SetMoveBoxMultiplier(2)
  STATE:SetStateMinSp(0)
  STATE:SetChargeTimer(false)
  STATE:InitLua(40, 0, 900, false, true, 0)
  STATE:InitLuaInputSecond(0, 0, 0, "HM_DMGeffect_Dummy", "")
end
function StandardBreakerAfterDash4(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetDrop(400, MAKEVECTOR3(0, -10000, 0))
  STATE:SetMoveBoxMultiplier(1)
  STATE:SetStealthCancel(true)
  STATE:SetHitStop(600, 700)
  STATE:SetCheckChargeAttack(true)
  STATE:SetSettingChargeTime(true)
  STATE:EnableCameraShake(true, false, 560)
  STATE:SetCameraShakeFactor1(300, 50, 60)
  STATE:SetCameraShakeFactor2(60, 0, 2000, 3000)
  STATE:InitLua("", "", 800, 1000, 40, false, 2000)
  STATE:SetSpendSp(50)
  local range = WEAPON:GetRange()
  Attack1 = CreateCAttack()
  Attack1:InitAttack1(WEAPONTYPE_BREAKER, ATTACKATTRIB_BREAKER_SWORD_ATTACK4, 600, Power + AdditionalPower, AdditionalPower)
  Attack1:InitAttack2(MAKEBOX(MAKEVECTOR3(0, 200, -100), MAKEVECTOR3(0, 0, -1), range * 1.5, range * 1.2, range * 1.7), 1, 1, false)
  Attack1:AddBlowCondition(0, 0)
  Attack1:SetFullCharge(false)
  AddAttack(ATTACKS, Attack1)
  Attack2 = CreateCAttack()
  Attack2:InitAttack1(WEAPONTYPE_BREAKER, ATTACKATTRIB_BREAKER_SWORD_ATTACK4, 600, Power + AdditionalPower, AdditionalPower)
  Attack2:InitAttack2(MAKEBOX(MAKEVECTOR3(0, 200, -100), MAKEVECTOR3(0, 0, -1), range * 1.5, range * 1.2, range * 1.7), 1, 1, false)
  Attack2:AddBlowCondition(0, 0)
  Attack2:SetFullCharge(true)
  AddAttack(ATTACKS, Attack2)
end
function StandardBreakerAfterDash5(OneShotTime, Power, Accuracy, AdditionalPower)
  STATE:SetMoveSpeedRate(0.85)
  STATE:SetStealthCancel(true)
  STATE:SetHitStop(150, 300)
  STATE:SetMoveBoxMultiplier(2)
  STATE:SetStateMinSp(50)
  STATE:SetChargeTimer(true)
  STATE:InitLua(40, 0, 2000, false, true, 3)
  STATE:InitLuaInputSecond(2000, 0, 0, "HM_DMGeffect_Dummy", "")
end
